### ISSUE TITLE
Remove dependency from Bootstrap sass

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/ehealth-bootstrap#1]
[Here](https://github.com/eHealthAfrica/ehealth-bootstrap/blob/master/bower.json#L29)

If not removed, the extra bootstrap will be downloaded and installed by Bower, and sometimes automatically wired in apps bringing bugs

**Comment by codebeige** [comment]
This should be fixed in 0.0.4, right? Can we close this issue then?

**Comment by danse** [comment]
Yep, tag `0.0.4` looks fine, `master` is still behind though

**Comment by codebeige** [comment]
@espy `master` should probably link to the latest release namely `0.0.4`as well. What do you think?

**Comment by espy** [comment]
Yeh, I should have just put this on master. There's still some stuff missing (touch buttons and checkboxes), but that should just go in `0.0.5`. 

Let me just fix that…

**Comment by espy** [comment]
Done, and the `0.0.4` release is linked to master.
