### ISSUE TITLE
navbar becomes misaligned using different branding/fonts

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/ehealth-bootstrap#16]
If the navbar does not contain an image in `navbar-header > navbar-brand`, it becomes misaligned:

![screen shot 2015-05-06 at 15 02 26](https://cloud.githubusercontent.com/assets/323761/7493921/cefeecac-f404-11e4-8a5f-186d3ef450f8.png)

This also occurs when `$font-size-base` is changed, as in the case of direct-delivery (https://github.com/eHealthAfrica/ehealth-bootstrap/pull/4):

![screen shot 2015-02-19 at 10 29 40](https://cloud.githubusercontent.com/assets/323761/6265097/4f6b2aaa-b822-11e4-9d41-09e2b5d397a2.png)

**Comment by bnvk** [comment]
@tlvince in the NutSurv Mobile app this should be solved by adding an icon in the navbar. The icon for NutSurv is:

![NutSurv icon](https://raw.githubusercontent.com/eHealthAfrica/design/master/renders/app-journal-192.png?token=AAC-JXvcfxTRO0cAzvSiBfjILgW-AbkAks5VVHH5wA%3D%3D)

In the Direct Delivery app, why is the `$font-size-base` changed?

**Comment by tlvince** [comment]
`$font-size-base` is changed per user feedback; the app is used primarily outdoors on a tablet and the default size was found to be too small.

**Comment by tlvince** [comment]
Re nutsurv, agreed, adding an image will resolve this, but we've stringent requirements and there may be a reason the home icon is used. Will followup.

**Comment by FrancescoK** [comment]
The $font-size-base was changed for the same reason in Sense ID (BiometricRegistration), btw.

**Comment by bnvk** [comment]
@FrancescoK are you aware of what reason that is?

**Comment by FrancescoK** [comment]
Just as Tom said, on tablets it was just really tiny, several people complained about it. Bumped it to 16 or 17px iirc.

**Comment by bnvk** [comment]
@FrancescoK @tlvince OK, this really should be a non-problem with using my icons, as they're 24px high, which is why I had to auto center the `App Name` text, which is what is now screwed up. I made it bigger on purpose for this reason!

**Comment by tlvince** [comment]
So you're saying the issue will be resolved iff we use the app icons, regardless of `$font-size-base`?

**Comment by cristinasantamarina** [comment]
The home page is made as per Robert's spec and it is one of the pages for which we have a sign off. I am hesitant to make changes in the version of the app we will deploy.

**Comment by RobertJohnston** [comment]
Sorry, I made this crystal clear in the specifications and on the phone
with Cristina that the home page should follow the specifications.  So
there is no sign off on the home page.

If this cannot be corrected before the delivery date, it will need to be
changed after.

Thanks

**Comment by cristinasantamarina** [comment]
Robert you said the home page was good to go in the call we had in which we
went through the apk and the ux doc. This to me is a sign off. We just need
to make sure the image looks ok on the tablet. Other than thay what other
changes are needed otherwise?

**Comment by RobertJohnston** [comment]
Hey Cristina,

When we discussed the home page about 2 months ago, we agreed that alerts
would not go on the home page. I updated the specs document - sent to you
and archived on google docs.

When we discussed on the phone, I brought up again that this issue had not
been corrected.  You mentioned that it would require hiring someone to do
more work and would likely not happen before the delivery date.  I make it
clear that the dashboard including the home page should follow the specs
even if that could not be completed before the delivery date.

Thanks

**Comment by jjal** [comment]
Hi all this repo is for the parent ehealth bootstrap theme and should not include changes or discussions for individual projects, which can override the bits they need to. Sounds like a separate parent bootstrap-mobile might be warranted too fwiw.
